exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
- "**/UserHelper.kt"
- "**HiltComponents"

plugins:
  duplication:
    enabled: true
    config:
      languages:
        kotlin:
          mass_threshold: 40
