version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 60
    identical-code:
      config:
        threshold: 80

exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
- "**UserHelper"
- "**/di/"


