package ch.epfl.sdp.blindly.user.enums

import ch.epfl.sdp.blindly.R

enum class Passions(val asString: String, val id: Int) {
    BRUNCH("Brunch", R.id.brunch_chip),
    WINE("Wine"  , R.id.wine_chip),
    FASHION("Fashion", R.id.fashion_chip),
    CYCLING("Cycling", R.id.cycling_chip),
    RUNNING("Running", R.id.running_chip),
    TEA("Tea", R.id.tea_chip),
    COFFEE("Coffee", R.id.coffee_chip),
    COMEDY("Comedy", R.id.comedy_chip),
    WALKING("Walking", R.id.walking_chip),
    BOARD_GAMES("Board Games", R.id.board_games_chip),
    YOGA("Yoga", R.id.yoga_chip),
    KARAOKE("Karaoke", R.id.karaoke_chip),
    DOG_LOVER("Dog Lover", R.id.dog_lover_chip),
    GAMER("Gamer", R.id.gamer_chip),
    ART("Art", R.id.art_chip),
    COCKTAILS("Cocktails", R.id.cocktails_chip),
    DANCING("Dancing", R.id.dancing_chip),
    PHOTOGRAPHY("Photography", R.id.photo_chip),
    WRITER("Writer", R.id.writer_chip),
    FOODIE("Foodie", R.id.foodie_chip),
    BAKING("Baking", R.id.baking_chip),
    SWIMMING("Swimming", R.id.swimming_chip),
    NETFLIX("Netflix", R.id.netflix_chip),
    OUTDOORS("Outdoors", R.id.outdoors_chip),
    MUSIC("Music", R.id.music_chip),
    MOVIES("Movies", R.id.movies_chip),
    CLIMBING("Climbing", R.id.climbing_chip),
    FISHING("Fishing", R.id.fishing_chip),
    CAT_LOVER("Cat Lover", R.id.cat_lover_chip),
    READING("Reading", R.id.reading_chip),
    FOOTBALL("Football", R.id.football_chip),
    SPIRITUALITY("Spirituality", R.id.spirituality_chip),
    GARDENING("Gardening", R.id.gardening_chip),
}